"""create_qr_tokens_table

Revision ID: 4a69b13a69fd
Revises: cb7bfc2971ab
Create Date: 2026-04-15 16:12:08.369442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a69b13a69fd'
down_revision: Union[str, Sequence[str], None] = 'cb7bfc2971ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_student_id'), 'qr_tokens', ['student_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_token'), 'qr_tokens', ['token'], unique=True)
    op.drop_index(op.f('ix_event_logs_actor_user_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_project_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_student_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_constraint(op.f('students_google_id_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_google_id'), 'students', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_google_id'), table_name='students')
    op.create_unique_constraint(op.f('students_google_id_key'), 'students', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('event_logs_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('event_logs_project_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('event_logs_student_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('event_logs_pkey'))
    )
    op.create_index(op.f('ix_event_logs_student_id'), 'event_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_event_logs_project_id'), 'event_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_actor_user_id'), 'event_logs', ['actor_user_id'], unique=False)
    op.drop_index(op.f('ix_qr_tokens_token'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_student_id'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    # ### end Alembic commands ###
