"""create core tables

Revision ID: 9f981c4ae365
Revises: 0c2e8499183f
Create Date: 2026-02-25 20:56:54.109378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f981c4ae365'
down_revision: Union[str, Sequence[str], None] = '0c2e8499183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_matricula'), 'students', ['matricula'], unique=True)
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('becario_user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['becario_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_becario_user_id'), 'checkins', ['becario_user_id'], unique=False)
    op.create_index(op.f('ix_checkins_student_id'), 'checkins', ['student_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_owner_user_id'), 'projects', ['owner_user_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_actor_user_id'), 'event_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_project_id'), 'event_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_logs_student_id'), 'event_logs', ['student_id'], unique=False)
    op.create_table('temp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_codes_code'), 'temp_codes', ['code'], unique=True)
    op.create_index(op.f('ix_temp_codes_created_by_user_id'), 'temp_codes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_temp_codes_project_id'), 'temp_codes', ['project_id'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('temp_code_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temp_code_id'], ['temp_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_project_id'), 'registrations', ['project_id'], unique=False)
    op.create_index(op.f('ix_registrations_student_id'), 'registrations', ['student_id'], unique=True)
    op.create_index(op.f('ix_registrations_temp_code_id'), 'registrations', ['temp_code_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_temp_code_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_student_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_project_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_temp_codes_project_id'), table_name='temp_codes')
    op.drop_index(op.f('ix_temp_codes_created_by_user_id'), table_name='temp_codes')
    op.drop_index(op.f('ix_temp_codes_code'), table_name='temp_codes')
    op.drop_table('temp_codes')
    op.drop_index(op.f('ix_event_logs_student_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_project_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_actor_user_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_projects_owner_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_checkins_student_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_becario_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_students_matricula'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
