#!/bin/bash
# ============================================
# Script de rotación de credenciales expuestas
# ============================================

echo "============================================"
echo "ROTACIÓN DE CREDENCIALES DE SEGURIDAD"
echo "============================================"
echo ""
echo "Este script ayuda a rotar credenciales expuestas."
echo "Sigue estos pasos:"
echo ""
echo "1. Genera un nuevo JWT_SECRET seguro:"
echo "   openssl rand -hex 32"
echo ""
echo "2. Actualiza el archivo .env con:"
echo "   - Nuevo JWT_SECRET"
echo "   - Nueva contraseña de base de datos (si fue expuesta)"
echo ""
echo "3. Acciones a realizar en Supabase:"
echo "   a) Ve a Project Settings -> Database"
echo "   b) Cambia la contraseña de postgres"
echo "   c) Actualiza DATABASE_URL en .env"
echo ""
echo "4. Después de actualizar .env:"
echo "   a) NO hagas commit de .env"
echo "   b) Verifica que .env está en .gitignore"
echo ""
echo "============================================"
echo "LIMPIAR HISTORIAL GIT DE CREDENCIALES"
echo "============================================"
echo ""
echo "Opción A - Usar git-filter-repo (recomendado):"
echo "   1. Instala git-filter-repo: pip install git-filter-repo"
echo "   2. Crea un archivo expressions.txt con:"
echo "      literal:CONTRASEÑA_ANTIGUA==>CONTRASEÑA_NUEVA"
echo "   3. Ejecuta: git filter-repo --replace-text expressions.txt"
echo ""
echo "Opción B - Usar BFG Repo-Cleaner:"
echo "   1. Descarga BFG: https://rtyley.github.io/bfg-repo-cleaner/"
echo "   2. java -jar bfg.jar --replace-text contraseñas.txt repo.git"
echo ""
echo "Opción C - Reescribir historial manualmente:"
echo "   1. git checkout --orphan new-main"
echo "   2. git add -A"
echo "   3. git commit -m 'Initial commit with clean history'"
echo "   4. git branch -m main old-main"
echo "   5. git branch -m new-main main"
echo "   6. git push origin main --force"
echo ""
echo "⚠️ ADVERTENCIA: Opciones A, B y C reescriben el historial de git."
echo "Todos los colaboradores deben clonar el repositorio nuevamente."
echo ""
read -p "Presiona Enter para continuar..."
